### ISSUE TITLE
Fix link to sitemap in main page

### ISSUE THREAD

**Issue by resinas** [isa-group/bpm2025#3]
I think sitemap is not working as expected. I see no reason why there is the indirection in the xml file

**Comment by ferferga** [comment]
@resinas The link is correctly generated, but in an indexed way and following Google's specs: https://developers.google.com/search/docs/crawling-indexing/sitemaps/large-sitemaps?hl=es-419 

There's also no way to (directly) hook into Astro's sitemap generation to change this behaviour, so I'm investigating we align with other SEO techniques first.

**Comment by ferferga** [comment]
The site is now being indexed properly: querying terms like "bpm 2025", "bpm conference 2025" and "bpm 2025 conferences", shows me now the page in the first position, so I'm closing this as not planned.
